//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoConsumidor.ServicioCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", ConfigurationName="ServicioCliente.ClienteCtl")]
    public interface ClienteCtl {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="crearCliente", ReplyAction="http://co.edu.eam.ingsoft.distribuidos/ClienteCtl/operacionCrearClienteResponse")]
        CarritoConsumidor.ServicioCliente.operacionCrearClienteResponse operacionCrearCliente(CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="crearCliente", ReplyAction="http://co.edu.eam.ingsoft.distribuidos/ClienteCtl/operacionCrearClienteResponse")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServicioCliente.operacionCrearClienteResponse> operacionCrearClienteAsync(CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operacionCrearClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operacionCrearCliente", Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        public CarritoConsumidor.ServicioCliente.operacionCrearClienteRequestBody Body;
        
        public operacionCrearClienteRequest() {
        }
        
        public operacionCrearClienteRequest(CarritoConsumidor.ServicioCliente.operacionCrearClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class operacionCrearClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string usuario;
        
        public operacionCrearClienteRequestBody() {
        }
        
        public operacionCrearClienteRequestBody(string cedula, string nombre, string apellido, string correo, string telefono, string usuario) {
            this.cedula = cedula;
            this.nombre = nombre;
            this.apellido = apellido;
            this.correo = correo;
            this.telefono = telefono;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operacionCrearClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="operacionCrearClienteResponse", Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        public CarritoConsumidor.ServicioCliente.operacionCrearClienteResponseBody Body;
        
        public operacionCrearClienteResponse() {
        }
        
        public operacionCrearClienteResponse(CarritoConsumidor.ServicioCliente.operacionCrearClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class operacionCrearClienteResponseBody {
        
        public operacionCrearClienteResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteCtlChannel : CarritoConsumidor.ServicioCliente.ClienteCtl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteCtlClient : System.ServiceModel.ClientBase<CarritoConsumidor.ServicioCliente.ClienteCtl>, CarritoConsumidor.ServicioCliente.ClienteCtl {
        
        public ClienteCtlClient() {
        }
        
        public ClienteCtlClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteCtlClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteCtlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteCtlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServicioCliente.operacionCrearClienteResponse CarritoConsumidor.ServicioCliente.ClienteCtl.operacionCrearCliente(CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest request) {
            return base.Channel.operacionCrearCliente(request);
        }
        
        public void operacionCrearCliente(string cedula, string nombre, string apellido, string correo, string telefono, string usuario) {
            CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest inValue = new CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest();
            inValue.Body = new CarritoConsumidor.ServicioCliente.operacionCrearClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.correo = correo;
            inValue.Body.telefono = telefono;
            inValue.Body.usuario = usuario;
            CarritoConsumidor.ServicioCliente.operacionCrearClienteResponse retVal = ((CarritoConsumidor.ServicioCliente.ClienteCtl)(this)).operacionCrearCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServicioCliente.operacionCrearClienteResponse> CarritoConsumidor.ServicioCliente.ClienteCtl.operacionCrearClienteAsync(CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest request) {
            return base.Channel.operacionCrearClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServicioCliente.operacionCrearClienteResponse> operacionCrearClienteAsync(string cedula, string nombre, string apellido, string correo, string telefono, string usuario) {
            CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest inValue = new CarritoConsumidor.ServicioCliente.operacionCrearClienteRequest();
            inValue.Body = new CarritoConsumidor.ServicioCliente.operacionCrearClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.correo = correo;
            inValue.Body.telefono = telefono;
            inValue.Body.usuario = usuario;
            return ((CarritoConsumidor.ServicioCliente.ClienteCtl)(this)).operacionCrearClienteAsync(inValue);
        }
    }
}
