//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoConsumidor.ServiceLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", ConfigurationName="ServiceLogin.LoginController")]
    public interface LoginController {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarritoConsumidor.ServiceLogin.operacionLoginResponse operacionLogin(CarritoConsumidor.ServiceLogin.operacionLogin request);
        
        [System.ServiceModel.OperationContractAttribute(Action="login", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceLogin.operacionLoginResponse> operacionLoginAsync(CarritoConsumidor.ServiceLogin.operacionLogin request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreUsuarioField;
        
        private string passwordField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string cedulaField;
        
        private string correoField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
                this.RaisePropertyChanged("cedula");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operacionLogin", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class operacionLogin {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        public operacionLogin() {
        }
        
        public operacionLogin(string nombre_usuario, string contrasenia) {
            this.nombre_usuario = nombre_usuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operacionLoginResponse", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class operacionLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceLogin.usuario @return;
        
        public operacionLoginResponse() {
        }
        
        public operacionLoginResponse(CarritoConsumidor.ServiceLogin.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginControllerChannel : CarritoConsumidor.ServiceLogin.LoginController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginControllerClient : System.ServiceModel.ClientBase<CarritoConsumidor.ServiceLogin.LoginController>, CarritoConsumidor.ServiceLogin.LoginController {
        
        public LoginControllerClient() {
        }
        
        public LoginControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceLogin.operacionLoginResponse CarritoConsumidor.ServiceLogin.LoginController.operacionLogin(CarritoConsumidor.ServiceLogin.operacionLogin request) {
            return base.Channel.operacionLogin(request);
        }
        
        public CarritoConsumidor.ServiceLogin.usuario operacionLogin(string nombre_usuario, string contrasenia) {
            CarritoConsumidor.ServiceLogin.operacionLogin inValue = new CarritoConsumidor.ServiceLogin.operacionLogin();
            inValue.nombre_usuario = nombre_usuario;
            inValue.contrasenia = contrasenia;
            CarritoConsumidor.ServiceLogin.operacionLoginResponse retVal = ((CarritoConsumidor.ServiceLogin.LoginController)(this)).operacionLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceLogin.operacionLoginResponse> CarritoConsumidor.ServiceLogin.LoginController.operacionLoginAsync(CarritoConsumidor.ServiceLogin.operacionLogin request) {
            return base.Channel.operacionLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceLogin.operacionLoginResponse> operacionLoginAsync(string nombre_usuario, string contrasenia) {
            CarritoConsumidor.ServiceLogin.operacionLogin inValue = new CarritoConsumidor.ServiceLogin.operacionLogin();
            inValue.nombre_usuario = nombre_usuario;
            inValue.contrasenia = contrasenia;
            return ((CarritoConsumidor.ServiceLogin.LoginController)(this)).operacionLoginAsync(inValue);
        }
    }
}
