//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoConsumidor.ServiceFactura {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controller.eam.edu.co/", ConfigurationName="ServiceFactura.FacturaController")]
    public interface FacturaController {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarritoConsumidor.ServiceFactura.validarItemsResponse validarItems(CarritoConsumidor.ServiceFactura.validarItems request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.validarItemsResponse> validarItemsAsync(CarritoConsumidor.ServiceFactura.validarItems request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarritoConsumidor.ServiceFactura.crearCompraResponse crearCompra(CarritoConsumidor.ServiceFactura.crearCompra request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.crearCompraResponse> crearCompraAsync(CarritoConsumidor.ServiceFactura.crearCompra request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CarritoConsumidor.ServiceFactura.eliminarCarritoResponse eliminarCarrito(CarritoConsumidor.ServiceFactura.eliminarCarrito request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.eliminarCarritoResponse> eliminarCarritoAsync(CarritoConsumidor.ServiceFactura.eliminarCarrito request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.eam.edu.co/")]
    public partial class itemsDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private double valorTotalField;
        
        private bool valorTotalFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
                this.RaisePropertyChanged("valorTotal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorTotalSpecified {
            get {
                return this.valorTotalFieldSpecified;
            }
            set {
                this.valorTotalFieldSpecified = value;
                this.RaisePropertyChanged("valorTotalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controller.eam.edu.co/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private decimal valorField;
        
        private bool valorFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
                this.RaisePropertyChanged("valorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarItems", WrapperNamespace="http://controller.eam.edu.co/", IsWrapped=true)]
    public partial class validarItems {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceFactura.itemsDTO[] arg0;
        
        public validarItems() {
        }
        
        public validarItems(CarritoConsumidor.ServiceFactura.itemsDTO[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarItemsResponse", WrapperNamespace="http://controller.eam.edu.co/", IsWrapped=true)]
    public partial class validarItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceFactura.producto @return;
        
        public validarItemsResponse() {
        }
        
        public validarItemsResponse(CarritoConsumidor.ServiceFactura.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearCompra", WrapperNamespace="http://controller.eam.edu.co/", IsWrapped=true)]
    public partial class crearCompra {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double total_factura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("detalles_factura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceFactura.itemsDTO[] detalles_factura;
        
        public crearCompra() {
        }
        
        public crearCompra(int id_usuario, double total_factura, CarritoConsumidor.ServiceFactura.itemsDTO[] detalles_factura) {
            this.id_usuario = id_usuario;
            this.total_factura = total_factura;
            this.detalles_factura = detalles_factura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearCompraResponse", WrapperNamespace="http://controller.eam.edu.co/", IsWrapped=true)]
    public partial class crearCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public crearCompraResponse() {
        }
        
        public crearCompraResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarrito", WrapperNamespace="http://controller.eam.edu.co/", IsWrapped=true)]
    public partial class eliminarCarrito {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controller.eam.edu.co/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public eliminarCarrito() {
        }
        
        public eliminarCarrito(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarritoResponse", WrapperNamespace="http://controller.eam.edu.co/", IsWrapped=true)]
    public partial class eliminarCarritoResponse {
        
        public eliminarCarritoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturaControllerChannel : CarritoConsumidor.ServiceFactura.FacturaController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturaControllerClient : System.ServiceModel.ClientBase<CarritoConsumidor.ServiceFactura.FacturaController>, CarritoConsumidor.ServiceFactura.FacturaController {
        
        public FacturaControllerClient() {
        }
        
        public FacturaControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturaControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturaControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturaControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceFactura.validarItemsResponse CarritoConsumidor.ServiceFactura.FacturaController.validarItems(CarritoConsumidor.ServiceFactura.validarItems request) {
            return base.Channel.validarItems(request);
        }
        
        public CarritoConsumidor.ServiceFactura.producto validarItems(CarritoConsumidor.ServiceFactura.itemsDTO[] arg0) {
            CarritoConsumidor.ServiceFactura.validarItems inValue = new CarritoConsumidor.ServiceFactura.validarItems();
            inValue.arg0 = arg0;
            CarritoConsumidor.ServiceFactura.validarItemsResponse retVal = ((CarritoConsumidor.ServiceFactura.FacturaController)(this)).validarItems(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.validarItemsResponse> CarritoConsumidor.ServiceFactura.FacturaController.validarItemsAsync(CarritoConsumidor.ServiceFactura.validarItems request) {
            return base.Channel.validarItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.validarItemsResponse> validarItemsAsync(CarritoConsumidor.ServiceFactura.itemsDTO[] arg0) {
            CarritoConsumidor.ServiceFactura.validarItems inValue = new CarritoConsumidor.ServiceFactura.validarItems();
            inValue.arg0 = arg0;
            return ((CarritoConsumidor.ServiceFactura.FacturaController)(this)).validarItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceFactura.crearCompraResponse CarritoConsumidor.ServiceFactura.FacturaController.crearCompra(CarritoConsumidor.ServiceFactura.crearCompra request) {
            return base.Channel.crearCompra(request);
        }
        
        public string crearCompra(int id_usuario, double total_factura, CarritoConsumidor.ServiceFactura.itemsDTO[] detalles_factura) {
            CarritoConsumidor.ServiceFactura.crearCompra inValue = new CarritoConsumidor.ServiceFactura.crearCompra();
            inValue.id_usuario = id_usuario;
            inValue.total_factura = total_factura;
            inValue.detalles_factura = detalles_factura;
            CarritoConsumidor.ServiceFactura.crearCompraResponse retVal = ((CarritoConsumidor.ServiceFactura.FacturaController)(this)).crearCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.crearCompraResponse> CarritoConsumidor.ServiceFactura.FacturaController.crearCompraAsync(CarritoConsumidor.ServiceFactura.crearCompra request) {
            return base.Channel.crearCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.crearCompraResponse> crearCompraAsync(int id_usuario, double total_factura, CarritoConsumidor.ServiceFactura.itemsDTO[] detalles_factura) {
            CarritoConsumidor.ServiceFactura.crearCompra inValue = new CarritoConsumidor.ServiceFactura.crearCompra();
            inValue.id_usuario = id_usuario;
            inValue.total_factura = total_factura;
            inValue.detalles_factura = detalles_factura;
            return ((CarritoConsumidor.ServiceFactura.FacturaController)(this)).crearCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceFactura.eliminarCarritoResponse CarritoConsumidor.ServiceFactura.FacturaController.eliminarCarrito(CarritoConsumidor.ServiceFactura.eliminarCarrito request) {
            return base.Channel.eliminarCarrito(request);
        }
        
        public void eliminarCarrito(int arg0, int arg1) {
            CarritoConsumidor.ServiceFactura.eliminarCarrito inValue = new CarritoConsumidor.ServiceFactura.eliminarCarrito();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CarritoConsumidor.ServiceFactura.eliminarCarritoResponse retVal = ((CarritoConsumidor.ServiceFactura.FacturaController)(this)).eliminarCarrito(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.eliminarCarritoResponse> CarritoConsumidor.ServiceFactura.FacturaController.eliminarCarritoAsync(CarritoConsumidor.ServiceFactura.eliminarCarrito request) {
            return base.Channel.eliminarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceFactura.eliminarCarritoResponse> eliminarCarritoAsync(int arg0, int arg1) {
            CarritoConsumidor.ServiceFactura.eliminarCarrito inValue = new CarritoConsumidor.ServiceFactura.eliminarCarrito();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CarritoConsumidor.ServiceFactura.FacturaController)(this)).eliminarCarritoAsync(inValue);
        }
    }
}
