//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoConsumidor.ServiceCarrito {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", ConfigurationName="ServiceCarrito.CarritoController")]
    public interface CarritoController {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarritoConsumidor.ServiceCarrito.listarCarritoResponse listarCarrito(CarritoConsumidor.ServiceCarrito.listarCarrito request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.listarCarritoResponse> listarCarritoAsync(CarritoConsumidor.ServiceCarrito.listarCarrito request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarritoConsumidor.ServiceCarrito.validarProductosResponse validarProductos(CarritoConsumidor.ServiceCarrito.validarProductos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.validarProductosResponse> validarProductosAsync(CarritoConsumidor.ServiceCarrito.validarProductos request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="AgregarCarrito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarritoConsumidor.ServiceCarrito.operacionAgregarCarritoResponse operacionAgregarCarrito(CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AgregarCarrito", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.operacionAgregarCarritoResponse> operacionAgregarCarritoAsync(CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos")]
    public partial class carrito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private producto productoField;
        
        private usuario usuarioField;
        
        private decimal valorTotalField;
        
        private bool valorTotalFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal valorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
                this.RaisePropertyChanged("valorTotal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorTotalSpecified {
            get {
                return this.valorTotalFieldSpecified;
            }
            set {
                this.valorTotalFieldSpecified = value;
                this.RaisePropertyChanged("valorTotalSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private decimal valorField;
        
        private bool valorFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
                this.RaisePropertyChanged("valorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string cedulaField;
        
        private string correoField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cedula {
            get {
                return this.cedulaField;
            }
            set {
                this.cedulaField = value;
                this.RaisePropertyChanged("cedula");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nombreUsuarioField;
        
        private string passwordField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCarrito", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class listarCarrito {
        
        public listarCarrito() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCarritoResponse", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class listarCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceCarrito.carrito[] @return;
        
        public listarCarritoResponse() {
        }
        
        public listarCarritoResponse(CarritoConsumidor.ServiceCarrito.carrito[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarProductos", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class validarProductos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceCarrito.carrito arg0;
        
        public validarProductos() {
        }
        
        public validarProductos(CarritoConsumidor.ServiceCarrito.carrito arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarProductosResponse", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class validarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validarProductosResponse() {
        }
        
        public validarProductosResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operacionAgregarCarrito", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class operacionAgregarCarrito {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceCarrito.carrito carrito;
        
        public operacionAgregarCarrito() {
        }
        
        public operacionAgregarCarrito(CarritoConsumidor.ServiceCarrito.carrito carrito) {
            this.carrito = carrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operacionAgregarCarritoResponse", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class operacionAgregarCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public operacionAgregarCarritoResponse() {
        }
        
        public operacionAgregarCarritoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarritoControllerChannel : CarritoConsumidor.ServiceCarrito.CarritoController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarritoControllerClient : System.ServiceModel.ClientBase<CarritoConsumidor.ServiceCarrito.CarritoController>, CarritoConsumidor.ServiceCarrito.CarritoController {
        
        public CarritoControllerClient() {
        }
        
        public CarritoControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarritoControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceCarrito.listarCarritoResponse CarritoConsumidor.ServiceCarrito.CarritoController.listarCarrito(CarritoConsumidor.ServiceCarrito.listarCarrito request) {
            return base.Channel.listarCarrito(request);
        }
        
        public CarritoConsumidor.ServiceCarrito.carrito[] listarCarrito() {
            CarritoConsumidor.ServiceCarrito.listarCarrito inValue = new CarritoConsumidor.ServiceCarrito.listarCarrito();
            CarritoConsumidor.ServiceCarrito.listarCarritoResponse retVal = ((CarritoConsumidor.ServiceCarrito.CarritoController)(this)).listarCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.listarCarritoResponse> CarritoConsumidor.ServiceCarrito.CarritoController.listarCarritoAsync(CarritoConsumidor.ServiceCarrito.listarCarrito request) {
            return base.Channel.listarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.listarCarritoResponse> listarCarritoAsync() {
            CarritoConsumidor.ServiceCarrito.listarCarrito inValue = new CarritoConsumidor.ServiceCarrito.listarCarrito();
            return ((CarritoConsumidor.ServiceCarrito.CarritoController)(this)).listarCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceCarrito.validarProductosResponse CarritoConsumidor.ServiceCarrito.CarritoController.validarProductos(CarritoConsumidor.ServiceCarrito.validarProductos request) {
            return base.Channel.validarProductos(request);
        }
        
        public bool validarProductos(CarritoConsumidor.ServiceCarrito.carrito arg0) {
            CarritoConsumidor.ServiceCarrito.validarProductos inValue = new CarritoConsumidor.ServiceCarrito.validarProductos();
            inValue.arg0 = arg0;
            CarritoConsumidor.ServiceCarrito.validarProductosResponse retVal = ((CarritoConsumidor.ServiceCarrito.CarritoController)(this)).validarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.validarProductosResponse> CarritoConsumidor.ServiceCarrito.CarritoController.validarProductosAsync(CarritoConsumidor.ServiceCarrito.validarProductos request) {
            return base.Channel.validarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.validarProductosResponse> validarProductosAsync(CarritoConsumidor.ServiceCarrito.carrito arg0) {
            CarritoConsumidor.ServiceCarrito.validarProductos inValue = new CarritoConsumidor.ServiceCarrito.validarProductos();
            inValue.arg0 = arg0;
            return ((CarritoConsumidor.ServiceCarrito.CarritoController)(this)).validarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceCarrito.operacionAgregarCarritoResponse CarritoConsumidor.ServiceCarrito.CarritoController.operacionAgregarCarrito(CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito request) {
            return base.Channel.operacionAgregarCarrito(request);
        }
        
        public bool operacionAgregarCarrito(CarritoConsumidor.ServiceCarrito.carrito carrito) {
            CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito inValue = new CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito();
            inValue.carrito = carrito;
            CarritoConsumidor.ServiceCarrito.operacionAgregarCarritoResponse retVal = ((CarritoConsumidor.ServiceCarrito.CarritoController)(this)).operacionAgregarCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.operacionAgregarCarritoResponse> CarritoConsumidor.ServiceCarrito.CarritoController.operacionAgregarCarritoAsync(CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito request) {
            return base.Channel.operacionAgregarCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceCarrito.operacionAgregarCarritoResponse> operacionAgregarCarritoAsync(CarritoConsumidor.ServiceCarrito.carrito carrito) {
            CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito inValue = new CarritoConsumidor.ServiceCarrito.operacionAgregarCarrito();
            inValue.carrito = carrito;
            return ((CarritoConsumidor.ServiceCarrito.CarritoController)(this)).operacionAgregarCarritoAsync(inValue);
        }
    }
}
