//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoConsumidor.ServiceCorreoTele {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.eam.edu.co/notificaciones", ConfigurationName="ServiceCorreoTele.notificaciones")]
    public interface notificaciones {
        
        // CODEGEN: El parámetro 'RespuestaNotificacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="enviarMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaNotificacion")]
        CarritoConsumidor.ServiceCorreoTele.enviarMailResponse enviarMail(CarritoConsumidor.ServiceCorreoTele.enviarMail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="enviarMail", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCorreoTele.enviarMailResponse> enviarMailAsync(CarritoConsumidor.ServiceCorreoTele.enviarMail request);
        
        // CODEGEN: El parámetro 'RespuestaNotificacion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="enviarSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaNotificacion")]
        CarritoConsumidor.ServiceCorreoTele.enviarSMSResponse enviarSMS(CarritoConsumidor.ServiceCorreoTele.enviarSMS request);
        
        [System.ServiceModel.OperationContractAttribute(Action="enviarSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCorreoTele.enviarSMSResponse> enviarSMSAsync(CarritoConsumidor.ServiceCorreoTele.enviarSMS request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eam.edu.co/notificaciones")]
    public partial class mail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyField;
        
        private string fromField;
        
        private string subjectField;
        
        private string toField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eam.edu.co/notificaciones")]
    public partial class sms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textoField;
        
        private string toField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
                this.RaisePropertyChanged("texto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.eam.edu.co/notificaciones")]
    public partial class respuestaNotificacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarMail", WrapperNamespace="http://www.eam.edu.co/notificaciones", IsWrapped=true)]
    public partial class enviarMail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.eam.edu.co/notificaciones", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceCorreoTele.mail correo;
        
        public enviarMail() {
        }
        
        public enviarMail(CarritoConsumidor.ServiceCorreoTele.mail correo) {
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarMailResponse", WrapperNamespace="http://www.eam.edu.co/notificaciones", IsWrapped=true)]
    public partial class enviarMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.eam.edu.co/notificaciones", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceCorreoTele.respuestaNotificacion RespuestaNotificacion;
        
        public enviarMailResponse() {
        }
        
        public enviarMailResponse(CarritoConsumidor.ServiceCorreoTele.respuestaNotificacion RespuestaNotificacion) {
            this.RespuestaNotificacion = RespuestaNotificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSMS", WrapperNamespace="http://www.eam.edu.co/notificaciones", IsWrapped=true)]
    public partial class enviarSMS {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.eam.edu.co/notificaciones", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceCorreoTele.sms sms;
        
        public enviarSMS() {
        }
        
        public enviarSMS(CarritoConsumidor.ServiceCorreoTele.sms sms) {
            this.sms = sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSMSResponse", WrapperNamespace="http://www.eam.edu.co/notificaciones", IsWrapped=true)]
    public partial class enviarSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.eam.edu.co/notificaciones", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceCorreoTele.respuestaNotificacion RespuestaNotificacion;
        
        public enviarSMSResponse() {
        }
        
        public enviarSMSResponse(CarritoConsumidor.ServiceCorreoTele.respuestaNotificacion RespuestaNotificacion) {
            this.RespuestaNotificacion = RespuestaNotificacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface notificacionesChannel : CarritoConsumidor.ServiceCorreoTele.notificaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class notificacionesClient : System.ServiceModel.ClientBase<CarritoConsumidor.ServiceCorreoTele.notificaciones>, CarritoConsumidor.ServiceCorreoTele.notificaciones {
        
        public notificacionesClient() {
        }
        
        public notificacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public notificacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public notificacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public notificacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceCorreoTele.enviarMailResponse CarritoConsumidor.ServiceCorreoTele.notificaciones.enviarMail(CarritoConsumidor.ServiceCorreoTele.enviarMail request) {
            return base.Channel.enviarMail(request);
        }
        
        public CarritoConsumidor.ServiceCorreoTele.respuestaNotificacion enviarMail(CarritoConsumidor.ServiceCorreoTele.mail correo) {
            CarritoConsumidor.ServiceCorreoTele.enviarMail inValue = new CarritoConsumidor.ServiceCorreoTele.enviarMail();
            inValue.correo = correo;
            CarritoConsumidor.ServiceCorreoTele.enviarMailResponse retVal = ((CarritoConsumidor.ServiceCorreoTele.notificaciones)(this)).enviarMail(inValue);
            return retVal.RespuestaNotificacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCorreoTele.enviarMailResponse> CarritoConsumidor.ServiceCorreoTele.notificaciones.enviarMailAsync(CarritoConsumidor.ServiceCorreoTele.enviarMail request) {
            return base.Channel.enviarMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceCorreoTele.enviarMailResponse> enviarMailAsync(CarritoConsumidor.ServiceCorreoTele.mail correo) {
            CarritoConsumidor.ServiceCorreoTele.enviarMail inValue = new CarritoConsumidor.ServiceCorreoTele.enviarMail();
            inValue.correo = correo;
            return ((CarritoConsumidor.ServiceCorreoTele.notificaciones)(this)).enviarMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceCorreoTele.enviarSMSResponse CarritoConsumidor.ServiceCorreoTele.notificaciones.enviarSMS(CarritoConsumidor.ServiceCorreoTele.enviarSMS request) {
            return base.Channel.enviarSMS(request);
        }
        
        public CarritoConsumidor.ServiceCorreoTele.respuestaNotificacion enviarSMS(CarritoConsumidor.ServiceCorreoTele.sms sms) {
            CarritoConsumidor.ServiceCorreoTele.enviarSMS inValue = new CarritoConsumidor.ServiceCorreoTele.enviarSMS();
            inValue.sms = sms;
            CarritoConsumidor.ServiceCorreoTele.enviarSMSResponse retVal = ((CarritoConsumidor.ServiceCorreoTele.notificaciones)(this)).enviarSMS(inValue);
            return retVal.RespuestaNotificacion;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceCorreoTele.enviarSMSResponse> CarritoConsumidor.ServiceCorreoTele.notificaciones.enviarSMSAsync(CarritoConsumidor.ServiceCorreoTele.enviarSMS request) {
            return base.Channel.enviarSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceCorreoTele.enviarSMSResponse> enviarSMSAsync(CarritoConsumidor.ServiceCorreoTele.sms sms) {
            CarritoConsumidor.ServiceCorreoTele.enviarSMS inValue = new CarritoConsumidor.ServiceCorreoTele.enviarSMS();
            inValue.sms = sms;
            return ((CarritoConsumidor.ServiceCorreoTele.notificaciones)(this)).enviarSMSAsync(inValue);
        }
    }
}
