//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoConsumidor.ServiceProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", ConfigurationName="ServiceProducto.ProductoController")]
    public interface ProductoController {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="listarProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CarritoConsumidor.ServiceProducto.operacionListarProductosResponse operacionListarProductos(CarritoConsumidor.ServiceProducto.operacionListarProductos request);
        
        [System.ServiceModel.OperationContractAttribute(Action="listarProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceProducto.operacionListarProductosResponse> operacionListarProductosAsync(CarritoConsumidor.ServiceProducto.operacionListarProductos request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private bool cantidadFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int idAuxField;
        
        private bool idAuxFieldSpecified;
        
        private string nombreField;
        
        private decimal valorField;
        
        private bool valorFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("cantidadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAux {
            get {
                return this.idAuxField;
            }
            set {
                this.idAuxField = value;
                this.RaisePropertyChanged("idAux");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAuxSpecified {
            get {
                return this.idAuxFieldSpecified;
            }
            set {
                this.idAuxFieldSpecified = value;
                this.RaisePropertyChanged("idAuxSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
                this.RaisePropertyChanged("valorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operacionListarProductos", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class operacionListarProductos {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreProducto;
        
        public operacionListarProductos() {
        }
        
        public operacionListarProductos(string nombreProducto) {
            this.nombreProducto = nombreProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="operacionListarProductosResponse", WrapperNamespace="http://co.edu.eam.ingsoft.distribuidos", IsWrapped=true)]
    public partial class operacionListarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://co.edu.eam.ingsoft.distribuidos", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarritoConsumidor.ServiceProducto.producto[] @return;
        
        public operacionListarProductosResponse() {
        }
        
        public operacionListarProductosResponse(CarritoConsumidor.ServiceProducto.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoControllerChannel : CarritoConsumidor.ServiceProducto.ProductoController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoControllerClient : System.ServiceModel.ClientBase<CarritoConsumidor.ServiceProducto.ProductoController>, CarritoConsumidor.ServiceProducto.ProductoController {
        
        public ProductoControllerClient() {
        }
        
        public ProductoControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarritoConsumidor.ServiceProducto.operacionListarProductosResponse CarritoConsumidor.ServiceProducto.ProductoController.operacionListarProductos(CarritoConsumidor.ServiceProducto.operacionListarProductos request) {
            return base.Channel.operacionListarProductos(request);
        }
        
        public CarritoConsumidor.ServiceProducto.producto[] operacionListarProductos(string nombreProducto) {
            CarritoConsumidor.ServiceProducto.operacionListarProductos inValue = new CarritoConsumidor.ServiceProducto.operacionListarProductos();
            inValue.nombreProducto = nombreProducto;
            CarritoConsumidor.ServiceProducto.operacionListarProductosResponse retVal = ((CarritoConsumidor.ServiceProducto.ProductoController)(this)).operacionListarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarritoConsumidor.ServiceProducto.operacionListarProductosResponse> CarritoConsumidor.ServiceProducto.ProductoController.operacionListarProductosAsync(CarritoConsumidor.ServiceProducto.operacionListarProductos request) {
            return base.Channel.operacionListarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarritoConsumidor.ServiceProducto.operacionListarProductosResponse> operacionListarProductosAsync(string nombreProducto) {
            CarritoConsumidor.ServiceProducto.operacionListarProductos inValue = new CarritoConsumidor.ServiceProducto.operacionListarProductos();
            inValue.nombreProducto = nombreProducto;
            return ((CarritoConsumidor.ServiceProducto.ProductoController)(this)).operacionListarProductosAsync(inValue);
        }
    }
}
